version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    reviewers:
      - "ShadyBS"
    assignees:
      - "ShadyBS"
    labels:
      - "dependencies"
      - "automated"
    # Semantic versioning preferences
    versioning-strategy: increase-if-necessary
    # Group related updates
    groups:
      browser-extension-deps:
        patterns:
          - "browser-polyfill*"
          - "web-ext*"
          - "webpack*"
        update-types:
          - "minor"
          - "patch"
      testing-deps:
        patterns:
          - "jest*"
          - "playwright*"
          - "puppeteer*"
          - "eslint*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci:"
      include: "scope"
    reviewers:
      - "ShadyBS"
    assignees:
      - "ShadyBS"
    labels:
      - "ci"
      - "github-actions"
      - "automated"
